import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
    data-arp=""
    data-qb-extension-installed="true"
    data-qb-installed="true"
    >
      <body inmaintabuse="1" cz-shortcut-listen="true">
        <div className="container">
          <StoreProvider>{children}</StoreProvider>
        </div>
      </body>
    </html>
  );
}
